name: Build and Deploy
on:
  push:
    branches:
      - master

  # allow running workflow manually
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Angular Deploy gh-pages Actions
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
            
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        base_href: /canban2/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/canban2/browser # The folder where your project is supposed to be after running ng build by the action.

permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.
  pages: write
